FROM openjdk:8
MAINTAINER "Dinesh kumar Lear365@security.com"
EXPOSE 9000
WORKDIR /usr/local/bin/
COPY /target/learn365-education-security-0.0.1-SNAPSHOT.jar .
ENTRYPOINT ["java","-jar","learn365-education-security-0.0.1-SNAPSHOT.jar"]