FROM openjdk:8
MAINTAINER "Dinesh kumar Learn365@Subscription.com"
EXPOSE 9010
WORKDIR /usr/local/bin/
COPY target/learn365_subscription_service-0.0.1-SNAPSHOT.jar .
ENTRYPOINT ["java","-jar","learn365_subscription_service-0.0.1-SNAPSHOT.jar"]