FROM openjdk:8
MAINTAINER "Dinesh kumar Learn365@com"
EXPOSE 8090
WORKDIR /usr/local/bin/
COPY target/learn365-digital-gateway-0.0.1-SNAPSHOT.jar .
ENTRYPOINT ["java", "-jar", "learn365-digital-gateway-0.0.1-SNAPSHOT.jar"]