FROM openjdk:8
MAINTAINER "Dinesh kumar Learn365@registry.com"
EXPOSE 9096
WORKDIR /usr/local/bin/
COPY target/learn365_test_service-0.0.1-SNAPSHOT.jar .
ENTRYPOINT ["java","-jar","learn365_test_service-0.0.1-SNAPSHOT.jar"]