server:
   port: 9015
spring:
   application:
      name: learn365-subscription_services
   #datasource:
    #  driver: com.mysql.jdbc.Driver
     # url: jdbc:mysql://localhost:3306/learn365_subscription
      #username: root
      #password: R00t@1987
   #jpa:
    #  show-sql: true
     # hibernate:
      #   ddl-auto: update
      #properties:
       #  hibernate:
        #    dialect: org.hibernate.dialect.MySQL5Dialect
         #   naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
          #  format_sql: true
           # show_sql: true
            
            
learn365:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.ckbg4rgzbz67.ap-south-1.rds.amazonaws.com:3306/learn365_subscription
    username: learn365
    password: 0nlineeducation

    
  jpa:
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true
      show_sql: true
  security:
    ignore: /v2/api-docs,/configuration/ui,/swagger-resources/**,/configuration/security,/swagger-ui.html,/webjars/**,/v1/subscriptionportfolio/service/**,v1/userSubscription/service/**,/v1/service/**




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8999/eureka

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9000/oauth/check_token
    client:
      client-id: learn365onlineeducation
      client-secret: le1rnDigit1lCourse

logging:
  level:
    org:
      springframework:
        security: DEBUG