FROM openjdk:8
EXPOSE 9012
MAINTAINER "Dinesh Kumar Learn365@gmail.com"
WORKDIR /usr/local/bin/
COPY target/course_management_service-0.0.1-SNAPSHOT.jar .
ENTRYPOINT ["java","-jar","course_management_service-0.0.1-SNAPSHOT.jar"]

