FROM openjdk:8
MAINTAINER "Dinesh kumar Learn365@User.com"
EXPOSE 9010
WORKDIR /usr/local/bin/
COPY target/learn365-usermanager-0.0.1-SNAPSHOT.jar .
ENTRYPOINT ["java","-jar","learn365-usermanager-0.0.1-SNAPSHOT.jar"]