spring:
  profiles:
    active: local

---
spring:
  application:
    name: test-service
  profiles: default

---
spring:
  profiles: local
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testDb
    username: admin
    password: admin
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 9096

---
spring:
  profiles: test
  application:
    name: learn365-subscription_services

learn365:
  security:
    ignore: /v2/api-docs,/configuration/ui,/swagger-resources/**,/configuration/security,/swagger-ui.html,/webjars/**,/v1/subscriptionportfolio/service/**,v1/userSubscription/service/**,/v1/service/**

