FROM openjdk:8
MAINTAINER "Dinesh kumar Learn365@registry.com"
EXPOSE 8999
WORKDIR /usr/local/bin/
COPY target/learn365-registry-server-0.0.1-SNAPSHOT.jar .
ENTRYPOINT ["java","-jar","learn365-registry-server-0.0.1-SNAPSHOT.jar"]